### ISSUE TITLE
in multimonitor configuration clock is off screen

### ISSUE THREAD

**Issue by nshopik** [bhm/noflipqlo#10]
When using more than 1 monitor clock shows way off(on right) screen, you can only see current hour only. Seems centering incorrectly calculated.

**Comment by bhm** [comment]
I have a dual head at work, but I am yet to update to a dual back at my place. 

I am thinking weather this is SDL or screensaver daemon part.

**Comment by nshopik** [comment]
Small update running manually `/usr/lib/xscreensaver/noflipqlo -root` will produce correct result one clock centered across 2 desktops. I've lookup how xscreensaver start it in process list and notice xscreensaver always start 2 copies (one per monitor) So I guess its explains why it partially covered as it set width same as 2 displays and another copy will just cover it. Here output if monitors setup next to each other
```
Full Screen Resolution : 3840x1080
 Hour x coordinate 216
 Hour y coordinate 1212
 Minute x coordinate 1979
 Minute y coordinate 216
Background size 648
Time is: 19 : 4
Background size 648
Current time is 19 : 04
 stripped hour ? 19
dx = 27 : dy = 9
Text Coordinates x 1239 : y 225
dx = 27 : dy = 9
Text Coordinates x 2006 : y 225
Divider properties
        Height 5
        Width 3840
        Coordinate x 0
        Coordinate y 535
Background size 648
Background size 648
Current time is 19 : 04
 stripped hour ? 19
dx = 27 : dy = 9
Text Coordinates x 1239 : y 225
dx = 27 : dy = 9
Text Coordinates x 2006 : y 225
Divider properties
        Height 5
        Width 3840
        Coordinate x 0
        Coordinate y 535
```

I've made some changes in monitor setup and put them above each other so my resolution now 1920x2160 and it made it crash with error code 11 from xscreensaver. And running manually make it all numbers scrambled across each other
```
Full Screen Resolution : 1920x2160
 Hour x coordinate 432
 Hour y coordinate -365
 Minute x coordinate 990
 Minute y coordinate 432
Background size 1296
Time is: 19 : 21
Background size 1296
Current time is 19 : 21
 stripped hour ? 19
dx = 53 : dy = 19
Text Coordinates x -312 : y 451
dx = 53 : dy = 19
Text Coordinates x 1043 : y 451
Divider properties
        Height 11
        Width 1920
        Coordinate x 0
        Coordinate y 1069
Background size 1296
Background size 1296
Current time is 19 : 21
 stripped hour ? 19
dx = 53 : dy = 19
Text Coordinates x -312 : y 451
dx = 53 : dy = 19
Text Coordinates x 1043 : y 451
Divider properties
        Height 11
        Width 1920
        Coordinate x 0
        Coordinate y 1069
```

So I guess it should detect size of each monitor individually to make it work with xscreensaver

**Comment by nshopik** [comment]
After quick glance on SDL1.2 it seems impossible to detect different monitors, thus return correct resolutions for all copies of noflipqlo under xscreensaver. 

I've made several changes to make it actually compile under SDL 2.0 but it was kinda broken and require more changes, I'll update if I able actually make it work

**Comment by nshopik** [comment]
@bhm https://github.com/alexanderk23/gluqlo is fork/successor of your noflipqlo. Seems cleanup to pure C and fixes some issues.

**Comment by bhm** [comment]
Thanks, duder!
