### ISSUE TITLE
droid fonts are not working 

### ISSUE THREAD

**Issue by codemerlin** [bhm/noflipqlo#13]
So, on ubuntu 16.04 

```
Package fonts-droid is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-droid-fallback
```

then I installed fonts-droid-fallback

then  

`/usr/lib/xscreensaver/noflipqlo -ampm`

gave 

```
Full Screen Resolution : 1920x1080
TTF_OpenFont: Couldn't open /usr/share/fonts/truetype/droid/DroidSans-Bold.ttf
Background size 288
[1]    23035 segmentation fault (core dumped)  /usr/lib/xscreensaver/noflipqlo -ampm

```

could not work. then created a symlink 

`sudo ln -s /usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf /usr/share/fonts/truetype/droid/DroidSans-Bold.ttf`

it worked but display was totally jagged now 

![screenshot from 2016-08-07 12-31-57](https://cloud.githubusercontent.com/assets/919686/17464051/faf854f6-5c9a-11e6-9728-57aa5787a13a.png)

**Comment by bhm** [comment]
Looks like an issue with the languages/locales. You symlink to a fallback that may be for your language. I am seeing a `.in` domain in your email. 

Have you tried downloading a copy of the bold font and symlinking against it?

Otherwise it may be issue with SDL itself changing.

**Comment by nshopik** [comment]
Had same problem with 16.10 ubuntu release. Re-downloaded manually `DroidSans-Bold.ttf` to make it work, `fonts-droid-fallback` isn't fit here.

**Comment by bhm** [comment]
Thanks, @nshopik for this.

I sadly find little time to revisit old project at this point.

Closing this down.
